name: Rodar Script com GPU no Kaggle

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  executar-gpu:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar API do Kaggle
        run: pip install kaggle

      - name: Rodar Notebook na GPU do Kaggle
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        run: |
          # Envia seu notebook/script para rodar no Kaggle com GPU T4 ativada
          kaggle kernels push -p ./
